# 1. 텐서 만들기

In [6]:
# 헬퍼 함수
def describe(x):
    print("타입: {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print("값: \n{}".format(x))
    print()
          
import torch
describe(torch.Tensor(2,3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[2.0912e+20, 1.3086e-11, 4.3009e-05],
        [2.1668e-04, 1.3422e-05, 7.9883e+20]])



In [7]:
describe(torch.rand(2,3))  # [0,1) 범위 균등 분포
describe(torch.randn(2,3)) # 표준 정규 분포 (평균:0, 분산1)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.3079, 0.9800, 0.0950],
        [0.9769, 0.3197, 0.0495]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-1.7344, -0.3758, -1.1031],
        [-0.5358, -0.0181, -1.0475]])



In [14]:
describe(torch.zeros(2,3))

x = torch.ones(2,3)
describe(x)

# 인-플레이스 메소드(_붙음)
# 해당 텐서의 값을 바꿈.
# 1. 똑같은 값으로 채우기
x.fill_(5)
describe(x)

# 2. 정규 분포
x.normal_()
describe(x)

# 3. 균등 분포
x.uniform_()
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-0.9222, -0.0829, -1.0889],
        [-0.2669,  0.7799,  0.5220]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.4252, 0.6619, 0.8286],
        [0.1648, 0.7758, 0.7630]])



In [24]:
# 리스트로 텐서 만들기
x = torch.Tensor([[1,2,3],
                 [4,5,6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [15]:
# 넘파이로 텐서 만들기
import numpy as np

npy = np.random.rand(2,3)
# array([[0.87091775, 0.71359683, 0.18997446],
#       [0.04928487, 0.03445624, 0.10588984]])

describe(torch.from_numpy(npy))
# DoubleTensor로 타입이 변경됨.
# 넘파이 배열의 기본 타입이 float64이기 때문.

타입: torch.DoubleTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.6848, 0.5579, 0.3614],
        [0.9748, 0.4449, 0.8236]], dtype=torch.float64)



# 2. 텐서 타입과 크기

In [23]:
x = torch.FloatTensor([[1,2,3],
                      [4,5,6]])
describe(x)

# 타입 캐스팅 메소드1
x = x.long()
describe(x)

# 아예 torch.int64 타입 명시 --> torch.LongTensor 타입
# torch.tensor(__, dtype=__) O, torch.Tensor(__, dtype=__) X
x = torch.tensor([[1,2,3],
                 [4,5,6]], dtype=torch.int64)
describe(x)

# 타입 캐스팅 메소드2
x = x.float()
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



# 3. 텐서 연산

In [25]:
x = torch.randn(2,3)
describe(x)

describe(torch.add(x,x))

describe(x+x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.5236,  0.4885,  0.9260],
        [ 0.0569,  0.0909, -1.8697]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 1.0472,  0.9769,  1.8519],
        [ 0.1137,  0.1817, -3.7393]])

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 1.0472,  0.9769,  1.8519],
        [ 0.1137,  0.1817, -3.7393]])



In [28]:
# 차원별 연산

x = torch.arange(6)
describe(x)
#tensor([0, 1, 2, 3, 4, 5]) --> LongTensor
# Q. 책에서는 왜 FloatTensor 타입이지?

# view(): 동일한 데이터를 공유하는 새로운 텐서 만듦.
# --> data.ptr() 사용시 원본 텐서와 뷰 텐서가 같은 저장위치임을 확인 가능.
y = x.view(2,3)
describe(y)
# tensor([[0, 1, 2],
#         [3, 4, 5]])

# 두 텐서 모두 같은 저장 위치: 1830844865600
print(x.data_ptr())
print(y.data_ptr())
print()

# 1) 행과 행 더하기 (dim=0)
describe(torch.sum(y, dim=0))  # tensor([3, 5, 7])
# 2) 열과 열 더하기 (dim=1)
describe(torch.sum(y, dim=1))  # tensor([ 3, 12])

# 0차원(행)과 1차원(열) 전치
describe(torch.transpose(y, 0, 1))
# tensor([[0, 3],
#         [1, 4],
#         [2, 5]])

타입: torch.LongTensor
크기: torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])

1830844869440
1830844869440

타입: torch.LongTensor
크기: torch.Size([3])
값: 
tensor([3, 5, 7])

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([ 3, 12])

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])



# 4. 인덱싱, 슬라이싱, 연결

## 4.1. 인덱싱과 슬라이싱

In [30]:
x = torch.arange(6).view(2,3)
describe(x)

describe(x[:1,:2])  # tensor([[0, 1]])

describe(x[0,1])    # 1
# torch.Size([])

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])

타입: torch.LongTensor
크기: torch.Size([1, 2])
값: 
tensor([[0, 1]])

타입: torch.LongTensor
크기: torch.Size([])
값: 
1



In [31]:
# 복잡한 인덱싱
# 불연속 텐서 인덱스 참조하기
# torch.index_select([텐서], dim=0/1, index=___)

indices = torch.LongTensor([0,2])
describe(torch.index_select(x, dim=1, index=indices))
# 0열과 2열 선택하기

indices = torch.LongTensor([0,0])
describe(torch.index_select(x, dim=0, index=indices))
# 0행과 0행 선택하기

row_indices = torch.arange(2).long()  # tensor([0,1])
col_indices = torch.LongTensor([0,1])
describe(x[row_indices, col_indices]) # x[[0,1],[0,1]]
# x의 0행과 1행, 그것의 0열과 1열
# --> tensor([0, 4])

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2]])

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([0, 4])



In [40]:
# 인덱싱, 슬라이싱 기초 정리

x = tensor.arange(6).view(2,3)
# tensor([[0, 1, 2],
#         [3, 4, 5]])
x[0,1] # 0행 1열 # tensor(1)
x[0][1] # tensor(1)
x[0]   # tensor([0, 1, 2])
x[1]   # tensor([3, 4, 5])
# x[2] # 인덱스에러
x[1:]  # tensor([[3, 4, 5]])
x[[0]] # tensor([[0, 1, 2]])
x[[1]] # tensor([[3, 4, 5]])
x[[0,1]] # 0행 & 1행
         # tensor([[0, 1, 2],
         # [3, 4, 5]])
# x[[0][1]] # 인덱스에러
# x[[0:1]] # 신택스에러
x[[0,1],[0,1]] # 0행&1행의 각 0열&1열
               # 0행의 0행, 1행의 1행
               # tensor([0, 4])
# x[[0,1],[0,1,2]] # 인덱스에러 (shape mismatch)

tensor(1)

## 4.2. 텐서 연결

In [59]:
x = torch.arange(6).view(2,3)
describe(x)

describe(torch.cat([x,x], dim=0))
# 크기: torch.Size([4, 3])
# tensor([[0, 1, 2],
#         [3, 4, 5],
#         [0, 1, 2],
#         [3, 4, 5]])
describe(torch.cat([x,x], dim=1))
# 크기: torch.Size([2, 6])
# tensor([[0, 1, 2, 0, 1, 2],
#         [3, 4, 5, 3, 4, 5]])

describe(torch.stack([x,x]))
# 크기: torch.Size([2, 2, 3])
# tensor([[[0, 1, 2],
#          [3, 4, 5]],

#         [[0, 1, 2],
#          [3, 4, 5]]])

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])

타입: torch.LongTensor
크기: torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

타입: torch.LongTensor
크기: torch.Size([2, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])

타입: torch.LongTensor
크기: torch.Size([2, 2, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])



## 4.3. 텐서의 선형 대수 계산: 행렬 곱셈

In [62]:
x1 = torch.arange(6).view(2,3).float()
describe(x1)
''' 왠지 모르겠는데 여기선 arange가 Long타입이 돼서 
곱셈 연산 위해 타입 맞춰주기 위해 float()으로 바꿔줌'''

x2 = torch.ones(3,2)
x2[:,1] += 1
describe(x2)

# 곱셈: (2,3)*(3,2)=(2,2) 사이즈
describe(torch.mm(x1,x2))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])

타입: torch.FloatTensor
크기: torch.Size([3, 2])
값: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[ 3.,  6.],
        [12., 24.]])



# 5. 텐서와 계산 그래프

In [71]:
# 그래디언트 연산 가능한 텐서 만들기

x = torch.ones(2,2, requires_grad=True)
describe(x)
# tensor([[1., 1.],
#         [1., 1.]], requires_grad=True)
print(x.grad is None)  # True

# 행렬끼리의 단순 원소별 곱셈*
# 선형대수의 행렬 곱셈 아님 주의!
# 1. 정방향 계산
y = (x+2) * (x+5) + 3
describe(y)
# tensor([[21., 21.],
#         [21., 21.]], grad_fn=<AddBackward0>)
print(x.grad is None)  # True

# z: 손실함수의 평가 결과로 얻은 텐서
z = y.mean()
describe(z)  # 21.0

# 2. 역방향 계산
z.backward()
print(x.grad is None) # False
# x.grad = 
# tensor([[2.2500, 2.2500],
#         [2.2500, 2.2500]])

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

True
타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)

True
타입: torch.FloatTensor
크기: torch.Size([])
값: 
21.0

False


## *그래디언트 (Gradient)
- 합수 입력에 대한 함수 출력의 기울기 
- --> 오류 신호에 대한 파라미터의 기여
- 모델의 파라미터마다 존재
- 계산 그래프 속 노드의 그래디언트 확인: .grad

### 그래디언트의 의미에 대해 더 찾아보기!