# 파이토치 기초 연습문제

1. 2D 텐서를 만들고 차원 0 위치에 크기가 1인 차원을 추가하세요.
- unsqueeze()

In [17]:
import torch

x = torch.Tensor(2,3) # 2행3열의 텐서
print(x)
# tensor([[7.7731e+34, 5.8014e-43, 7.7731e+34],
#         [5.8014e-43, 7.7734e+34, 5.8014e-43]])
print(x.shape)  # torch.Size([2, 3])

''' 
0(행)위치에 크기1 차원 추가하기: unsqueeze(0)
원본을 바꾸지는 않음! 
'''
print(x.unsqueeze(0))
# tensor([[[1.0315e-08, 1.3085e-11, 8.5753e-07],
#          [1.3167e-08, 1.0431e+21, 1.2794e+22]]])
print(x.unsqueeze(0).size())
# torch.Size([1, 2, 3])

tensor([[0.0000e+00, 1.0194e-38, 1.8754e+28],
        [6.4978e-07, 1.0315e-08, 1.3085e-11]])
torch.Size([2, 3])
tensor([[[0.0000e+00, 1.0194e-38, 1.8754e+28],
         [6.4978e-07, 1.0315e-08, 1.3085e-11]]])
torch.Size([1, 2, 3])


In [9]:
print(x.view(1,-1))
# tensor([[1.0315e-08, 1.3085e-11, 8.5753e-07, 
#          1.3167e-08, 1.0431e+21, 1.2794e+22]])
print(x.view(1,-1).size())  # torch.Size([1, 6])
print()

# x.view(1,-1,-1) : 오류
# RuntimeError: only one dimension can be inferred
# 하나의 차원만 추론될 수 있음! (-1)

'''위의 x.unsqueeze(0)과 같은 결과!'''
print(x.view(1, 2, -1))
# tensor([[[1.0315e-08, 1.3085e-11, 8.5753e-07],
#          [1.3167e-08, 1.0431e+21, 1.2794e+22]]])
print(x.view(1, 2, -1).size()) # torch.Size([1, 2, 3])

tensor([[1.0315e-08, 1.3085e-11, 8.5753e-07, 1.3167e-08, 1.0431e+21, 1.2794e+22]])
torch.Size([1, 6])

tensor([[[1.0315e-08, 1.3085e-11, 8.5753e-07],
         [1.3167e-08, 1.0431e+21, 1.2794e+22]]])
torch.Size([1, 2, 3])


In [12]:
print(x.unsqueeze(1))
# tensor([[[1.0315e-08, 1.3085e-11, 8.5753e-07]],

#         [[1.3167e-08, 1.0431e+21, 1.2794e+22]]])
print(x.unsqueeze(1).shape)
# torch.Size([2, 1, 3])
print()

print(x.unsqueeze(2))
# tensor([[[1.0315e-08],
#          [1.3085e-11],
#          [8.5753e-07]],

#         [[1.3167e-08],
#          [1.0431e+21],
#          [1.2794e+22]]])
print(x.unsqueeze(2).shape)
# torch.Size([2, 3, 1])
print()

'''다음과 동일한 결과'''
print(x.unsqueeze(-1))
print(x.unsqueeze(-1).shape)
# torch.Size([2, 3, 1])
print()

# print(x.unsqueeze(3))
# IndexError: Dimension out of range

tensor([[[1.0315e-08, 1.3085e-11, 8.5753e-07]],

        [[1.3167e-08, 1.0431e+21, 1.2794e+22]]])
torch.Size([2, 1, 3])

tensor([[[1.0315e-08],
         [1.3085e-11],
         [8.5753e-07]],

        [[1.3167e-08],
         [1.0431e+21],
         [1.2794e+22]]])
torch.Size([2, 3, 1])

tensor([[[1.0315e-08],
         [1.3085e-11],
         [8.5753e-07]],

        [[1.3167e-08],
         [1.0431e+21],
         [1.2794e+22]]])
torch.Size([2, 3, 1])



### squeeze(): 크기1 차원 제거

In [14]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [15]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


2. 이전 텐서에 추가한 차원을 삭제하세요.
- squeeze()

In [19]:
print(x)
x = x.unsqueeze(0)
print(x)
x = x.squeeze()
print(x)

tensor([[0.0000e+00, 1.0194e-38, 1.8754e+28],
        [6.4978e-07, 1.0315e-08, 1.3085e-11]])
tensor([[[0.0000e+00, 1.0194e-38, 1.8754e+28],
         [6.4978e-07, 1.0315e-08, 1.3085e-11]]])
tensor([[0.0000e+00, 1.0194e-38, 1.8754e+28],
        [6.4978e-07, 1.0315e-08, 1.3085e-11]])


3. 범위가 [3,7)이고 크기가 5x3인 랜덤한 텐서를 만드세요.

In [23]:
# [0,1) 범위 균등 분포
x = torch.rand(5,3)
print(x)

print(3+x*(7-3))

tensor([[0.1294, 0.9973, 0.9062],
        [0.2892, 0.3753, 0.5148],
        [0.1950, 0.7472, 0.7477],
        [0.6842, 0.6973, 0.5652],
        [0.4699, 0.1149, 0.4324]])
tensor([[3.5176, 6.9893, 6.6248],
        [4.1567, 4.5012, 5.0593],
        [3.7799, 5.9887, 5.9908],
        [5.7369, 5.7893, 5.2608],
        [4.8794, 3.4594, 4.7297]])


4. 정규 분포(평균=0, 표준편차=1)를 사용해 텐서를 만드세요.

In [24]:
# 방법1
x = torch.randn(2,3)
print(x)

tensor([[-1.9239,  0.9808, -0.6160],
        [ 0.4162, -0.0621,  2.2402]])


In [25]:
# 방법2
x = torch.rand(2,3)
x.normal_()

tensor([[-1.1760,  0.8718, -0.8003],
        [-0.5636,  2.8758, -1.6581]])

5. 텐서 torch.Tensor([1,1,1,0,1])에서 0이 아닌 원소의 인덱스를 추출하세요.

In [26]:
x = torch.Tensor([1,1,1,0,1])
torch.nonzero(x)

tensor([[0],
        [1],
        [2],
        [4]])

In [30]:
# nonzero 다른 예시
a = torch.Tensor([[1,2,0],
                 [2,0,0],
                 [0,0,0]])

'''이해할 수 없음--> 이해완료
각 행은 0아닌 값의 [행번호, 열번호]'''
print(torch.nonzero(a))
# tensor([[0, 0],
#         [0, 1],
#         [1, 0]])
'''행번호와 열번호를 따로 분리 -->
1차원 텐서에서 nonzero 찾을땐 굳이 안함'''
print(torch.nonzero(a, as_tuple=True))
# (tensor([0, 0, 1]), tensor([0, 1, 0]))
print(torch.count_nonzero(a))
# tensor(3)

tensor([[0, 0],
        [0, 1],
        [1, 0]])
(tensor([0, 0, 1]), tensor([0, 1, 0]))
tensor(3)


nonzero(): 0 아닌 값의 인덱스를 각 행에 담은 2차원 텐서 반환
- nonzero(__, as_tuple=True): 1차원 텐서 반환
- count_nonzero(): 0 아닌 값의 개수 계산

6. 크기가 (3,1)인 랜덤한 텐서를 만들고 네 벌을 복사해 쌓으세요.

In [31]:
x = torch.rand(3,1)
torch.stack([x,x,x,x])

tensor([[[0.5499],
         [0.9058],
         [0.7018]],

        [[0.5499],
         [0.9058],
         [0.7018]],

        [[0.5499],
         [0.9058],
         [0.7018]],

        [[0.5499],
         [0.9058],
         [0.7018]]])

In [32]:
x.expand(3,4)

tensor([[0.5499, 0.5499, 0.5499, 0.5499],
        [0.9058, 0.9058, 0.9058, 0.9058],
        [0.7018, 0.7018, 0.7018, 0.7018]])

In [33]:
x.expand(-1,4)

tensor([[0.5499, 0.5499, 0.5499, 0.5499],
        [0.9058, 0.9058, 0.9058, 0.9058],
        [0.7018, 0.7018, 0.7018, 0.7018]])

x.expand(): 크기가 1인 차원을 지정한 크기로 늘림. 
- 반환 텐서는 뷰--> 새로운 메모리 공간 점유 X
- 아래 torch.cat([x,x,x,x], dim=1)과 같은 결과

In [35]:
torch.cat([x,x,x,x], dim=1)

tensor([[0.5499, 0.5499, 0.5499, 0.5499],
        [0.9058, 0.9058, 0.9058, 0.9058],
        [0.7018, 0.7018, 0.7018, 0.7018]])

In [34]:
torch.cat([x,x,x,x], dim=0)

tensor([[0.5499],
        [0.9058],
        [0.7018],
        [0.5499],
        [0.9058],
        [0.7018],
        [0.5499],
        [0.9058],
        [0.7018],
        [0.5499],
        [0.9058],
        [0.7018]])

7. 2차원 행렬 두개(a=torch.rand(3,4,5), b=torch.rand(3,5,4))의 배치 행렬 곱셈을 계산하세요.

In [38]:
a=torch.rand(3,4,5)
b=torch.rand(3,5,4)

# 첫 차원 3을 배치 차원 처리
torch.bmm(a,b)
# 3*4*4 크기 텐서 출력

tensor([[[0.9641, 1.8260, 1.2953, 2.6239],
         [1.4579, 1.6706, 0.9796, 2.9465],
         [0.5560, 1.0568, 0.9934, 1.1877],
         [1.3446, 1.3377, 0.9296, 1.9636]],

        [[2.1124, 2.5755, 2.0525, 1.3854],
         [1.1710, 1.6644, 1.3303, 0.7471],
         [1.2840, 1.8811, 1.1700, 0.7338],
         [1.0356, 1.3333, 0.9187, 0.6954]],

        [[1.2093, 1.2765, 0.6267, 1.1418],
         [0.7045, 0.7952, 0.4943, 0.4809],
         [0.8942, 0.5514, 0.4760, 0.7528],
         [0.9574, 0.6767, 0.6624, 0.7972]]])

Batch Matrix-Matrix product (bmm)
- 배치 행렬 곱셈: 첫번째 차원을 배치 차원으로 인식
- "배치 차원": 모든 텐서의 첫번째축(샘플축)
- "배치": 딥러닝 모델이 데이터셋을 처리하는 단위
- 두 텐서의 배치 차원의 크기(b)가 같아야 함!
- (b*n*m) x (b*m*p) --> (b*n*p) 크기
- 공식: torch.bmm(a,b)

8. 3차원 행렬(a=torch.rand(3,4,5))과 2차원 행렬(b=torch.rand(5,4))의 배치 행렬 곱셈을 계산하세요.

In [39]:
a=torch.rand(3,4,5)
b=torch.rand(5,4)

torch.bmm(a,b.unsqueeze(0).expand(a.size(0),*b.size()))
# a.size(0)=3, a.size(1)=4, a.size(2)=5
# (a.size(0),*b.size()) = (3, 5, 4)
# (1, 5, 4).expand(3, 5, 4)
# torch.bmm(a,b.unsqueeze(0).expand(3,-1,-1))과 같음

tensor([[[1.2690, 0.5915, 1.0790, 0.7796],
         [1.5243, 0.8203, 1.7320, 1.3944],
         [1.2951, 0.7531, 1.6503, 1.5653],
         [1.6362, 1.1462, 1.5153, 1.8671]],

        [[1.4285, 0.9550, 0.8773, 1.1609],
         [1.3492, 0.9135, 1.2597, 1.3740],
         [1.4138, 0.8853, 1.0783, 1.1916],
         [1.0297, 0.7511, 0.4533, 0.7155]],

        [[1.3936, 0.7293, 1.3525, 1.3076],
         [1.8024, 1.0326, 0.9601, 1.1667],
         [0.9364, 0.6968, 0.4234, 0.8494],
         [1.5914, 1.1919, 1.1488, 1.6544]]])

In [41]:
b.unsqueeze(0)

tensor([[[0.6057, 0.5216, 0.0650, 0.8649],
         [0.9918, 0.6676, 0.2204, 0.1506],
         [0.5891, 0.0254, 0.9419, 0.2816],
         [0.2386, 0.3485, 0.8103, 0.8387],
         [0.6873, 0.4114, 0.2352, 0.3176]]])